---
title: "Data Viz TOC"
author: "The Nature Conservancy's LANDFIRE team"
date: "4/5/2021"
output:
  html_document:
    theme: flatly
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

# Charts

## Animated line

For the code go [here](./code/animatedLine.R).

For example chart go [here](./charts/animatedLine.html).

* from https://www.r-graph-gallery.com/287-smooth-animation-with-tweenr.html
* ggplot
* uses scales to insert commas
* uses hrbrthemes for theme, including font
* uses scale limits
* saved (without parameters such as size)

## Chord

For the code go [here](./code/chord.R).

For example chart go [here](./charts/chord_interactive.html)

* uses chorddiag package https://www.r-graph-gallery.com/chord-diagram-interactive.html and https://github.com/mattflor/chorddiag
* this one has custom color palettes
* used saveWidget to save a copy

## Dumbbell

For the code go [here](./code/dumbbell.R).

For example chart go [here](./charts/dumbbell.html).

* see 
    * https://towardsdatascience.com/create-dumbbell-plots-to-visualize-group-differences-in-r-3536b7d0a19a
    * https://rpubs.com/ageek/ggplot-adv-part2
    * https://yonicd.github.io/ggalt/reference/geom_dumbbell.html
* has mostly uncustomized ggplot example
* has interactive plotly example
* added mean lines to both ggplot and plotly examples
* used scales to add commas
* plotly is complicated


## Sankey

For the code go [here](./code/sankey.R).

For example chart go [here](./charts/sankeyP.html).

* Interactive
* see https://www.r-graph-gallery.com/322-custom-colours-in-sankey-diagram.html
* also https://www.rdocumentation.org/packages/networkD3/versions/0.4/topics/sankeyNetwork
* unable to move left labels outside of chart (to the left of chart) as of 5 April 2021
* saved


## Waffle

For the code go [here](./code/waffle.R).

For example chart go [here](./charts/waffle.png)

* ggplot
* ggwaffle
* function to format numbers for y axis
* custom margins
* legend:
    * custom labels
    * moved
    * custom colors
* title, subtitle, caption
* added space between y-axis and chart
* ggsave

## Heatmap

For the code go [here](./code/heatmap.R).

For example chart go [here](./charts/coveHeatChart.png)

* ggplot
* pacman to load libraries, check for install and updates
* add character (e.g., "%") to axis labels
* reverse color ramp


## Grouped bar (useful for sclasses, ref vs. current)

For the code go [here](./code/groupedBar.R).

For example chart go [here](./charts/sclasplotHardwoods.png)

* subset to make chart of only one value (BpS in this example)
* set order of bars (then reverse)
* pivot data longer
* has line for facets (commented out)

## Ordered horizontal bar

## Bubble

# Maps

## Choropleth

For the code go [here](./code/choropleth.R).

For example map go [here](./maps)

* leaflet
* has multiple layers that are selectable
* states downloaded, not a loaded shapefile
* kinda large file size
* custom popups
* has crazy code for inserting a line of text at the bottom of the selection box
* custom colors 
* can't figure out how to have a dynamic legend that changes with selected map




